INSERT INTO STUDENT (ID_S, NUMBER_S, NAME_S) VALUES (1, 'TT-1', 'Paul'); --updated
INSERT INTO STUDENT (ID_S, NUMBER_S, NAME_S) VALUES (2, 'TT-2', 'Bob');
INSERT INTO STUDENT (ID_S, NUMBER_S, NAME_S) VALUES (3, 'TT-3', 'Pipe'); --deleted

INSERT INTO TEACHER (ID_T, NAME_T) VALUES (1, 'Hogan');
INSERT INTO TEACHER (ID_T, NAME_T) VALUES (2, 'Mila');
INSERT INTO TEACHER (ID_T, NAME_T) VALUES (3, 'Bob');
INSERT INTO TEACHER (ID_T, NAME_T) VALUES (4, 'Ma');
INSERT INTO TEACHER (ID_T, NAME_T) VALUES (5, 'Alex');

INSERT INTO COURSE (ID_C, NAME_C, DESCRIPTION_C, ID_T) VALUES (1, 'Math', 'Math-description', 1); --updated
INSERT INTO COURSE (ID_C, NAME_C, DESCRIPTION_C, ID_T) VALUES (2, 'Map', 'Map-description', 2);
INSERT INTO COURSE (ID_C, NAME_C, DESCRIPTION_C, ID_T) VALUES (3, 'English', 'English-description', 3); --deleted

INSERT INTO FEEDBACK (ID_F, COMMENT_F, VALUE_F) VALUES (1, 'a good student', 5); --updated
INSERT INTO FEEDBACK (ID_F, COMMENT_F, VALUE_F) VALUES (2, 'a good student', 4);

INSERT INTO STUDENT_COURSE_FEEDBACK (ID_C, ID_S, ID_F) VALUES (1, 1, 1);
INSERT INTO STUDENT_COURSE_FEEDBACK (ID_C, ID_S, ID_F) VALUES (2, 2, 2);
INSERT INTO STUDENT_COURSE_FEEDBACK (ID_C, ID_S, ID_F) VALUES (1, 3, null);
INSERT INTO STUDENT_COURSE_FEEDBACK (ID_C, ID_S, ID_F) VALUES (2, 3, null);
